import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} h-screen px-5 flex items-center justify-center bg-gradient-to-t from-indigo-500 via-purple-500 to-pink-500 bg-no-repeat`}
      >
        {children}
      </body>
    </html>
  );
}
